### ISSUE TITLE
Python program parameter: pecifying a non-existing file should load template

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gateplugin-Python#54]
This causes exception: 

```
ava.io.FileNotFoundException: JAR entry test.py not found in /home/johann/.m2/repository/uk/ac/gate/plugins/python/2.4-SNAPSHOT/python-2.4-SNAPSHOT.jar
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:144)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:152)
	at java.net.URL.openStream(URL.java:1068)
	at gate.plugin.python.PythonPr.getPythonProgramString(PythonPr.java:518)
	at gate.plugin.python.gui.PythonEditorVr.setTarget(PythonEditorVr.java:77)
	at gate.gui.NameBearerHandle.buildViews(NameBearerHandle.java:346)
	at gate.gui.NameBearerHandle.getLargeView(NameBearerHandle.java:187)
	at gate.gui.MainFrame.select(MainFrame.java:467)
	at gate.gui.MainFrame$22.processMouseEvent(MainFrame.java:1505)
	at gate.gui.MainFrame$22.mouseClicked(MainFrame.java:1348)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.Component.processMouseEvent(Component.java:6542)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by johann-petrak** [comment]
OK, turns out this is probably not a bug, but is caused by the weird behaviour of the dialog for a ResourceReference where entering a name directly into the input field, without opening the select a file dialog defaults to a creole: URL and not a file URL. This is unfortunately not what would be useful here in order to just create a new file, but nothing we can do, this is GATE behaviour.

**Comment by johann-petrak** [comment]
See https://github.com/GateNLP/gate-core/issues/133

**Comment by johann-petrak** [comment]
Updated documentation to explain this.

**Comment by johann-petrak** [comment]
Maybe subclass the ResourceReferenceChooser to assume a relative file path instead of creole for this parameter.

**Comment by ianroberts** [comment]
If this parameter is for a python file (which has to be on disk rather than in a JAR) then would it not make more sense for the parameter to be of type `URL` rather than `ResourceReference`?

**Comment by greenwoodma** [comment]
Yes we do this in some other plugins where the file has to be local on disk. The only reason to use a ResourceReference is if you want to support loading file from inside plugins. If you don't then use a URL.

**Comment by greenwoodma** [comment]
> Maybe subclass the ResourceReferenceChooser to assume a relative file path instead of creole for this parameter.

Just a further comment but this seems like a really terrible idea. The ResourceReferenceChooser is added to the UI automatically because of the param type. I don't think subclassing would work. You'd either need to define an entirely new type to use a subclass of the chooser or hard code the exception inside the existing instance. Either of those seem like rather hacky solutions. I'd certainly try using a URL first, although I'm not sure a relative path works in that instance either as it will probably end up passing through the same util method. To be honest I don't think relative paths have ever worked the way you expect since the first Java version of GATE.

**Comment by johann-petrak** [comment]
It is a ResourceReference because the Python plugin has prepared pipelines and may have prepared Python scripts. Like read-only files, Python scripts from the JAR can be used but not edited. 

I guess you are right though, there is probably no good way to make this work.
